#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"../../os/syscall_ids.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exec");
entry("exit");
entry("wait");
# entry("kill");  # 原始的kill不再需要，使用sigkill代替
entry("getpid");
entry("getppid");
entry("sleep");
entry("yield");
entry("sbrk");
entry("mmap");
entry("read");
entry("write");
entry("gettimeofday");
entry("ktest");

# signals:
entry("sigaction");
entry("sigreturn");
entry("sigkill");
entry("sigpending");
entry("sigprocmask");

# kill已经在syscall.h中定义为内联函数，不需要这里的定义